# -*- coding: utf-8 -*-
"""Content dictionaries for every service & category page."""

CR_HOME = []
SEPTIC_CRUMB = [("Septic Services", "septic-services.html")]
WELL_CRUMB = [("Well Drilling", "well-drilling.html")]
GREASE_CRUMB = [("Grease Interceptors", "grease-interceptors.html")]

PAGES = [

# ---------- SEPTIC SERVICES (category) ----------
{
 "file":"septic-services.html","active":"septic-services.html",
 "direct_answer":[('When should you call for septic service?', "Call Sharpe's when it has been several years since your last pumping, when you notice slow drains, odors, or wet spots over the drain field, or when you are buying or selling a property and need an inspection. We serve homeowners and businesses across Columbia, Gaston, Lexington, and the surrounding Midlands, and we'll help you pinpoint the right service.")],
 "title":"Septic Services in the Midlands | Sharpe's Septic",
 "desc":"Septic pumping, repairs, replacement, installation, and inspections for homes and businesses across the Midlands. Family owned since 1966. Call (803) 755-1615.",
 "h1":"Septic Services","eyebrow":"Residential &amp; commercial septic",
 "crumbs":CR_HOME,"service_param":"","photo":"Sharpe's truck and crew on septic job site",
 "photo_key":"septic_team","photo_alt":"Sharpe's Septic Tank and Well Drilling service team on a residential job site",
 "hero_copy":"Whatever your septic system needs — routine pumping, a repair, a full replacement, a new install, or an inspection — Sharpe's handles it with the experience of a local team that's been doing this since 1966.",
 "cta_label":"Schedule Septic Service","cta_track":"request_estimate_click",
 "context":{"eyebrow":"One team for your whole system","title":"Septic care from pumping to full installation",
   "body":"A healthy septic system protects your property, your water, and your wallet. We help you keep yours running and step in quickly when something goes wrong. We serve homeowners and businesses across Columbia, Gaston, Lexington, and the surrounding Midlands.",
   "points":["Routine pumping to prevent backups","Repairs and full system replacement","New septic system installation","Inspections for buying, selling, or maintenance","Lift stations, Letts systems, and sewer connections"]},
 "cards_title":"Explore septic services","cards_eyebrow":"Choose your service","cards_cols":4,
 "cards":[
   ("Septic Installation","New system design and installation sized for your property and soil conditions.","septic-installation.html"),
   ("Repairs &amp; Replacement","Fixes for failing components and full replacement when a system has reached the end of its life.","septic-repairs-replacement.html"),
   ("Septic Pumping","Regular pumping that keeps solids in check and prevents costly backups.","septic-pumping.html"),
   ("Septic Inspections","Clear, documented inspections for real estate transactions and peace of mind.","septic-inspections.html"),
 ],
 "signs":{"title":"Signs your septic system needs attention","items":[
   "Slow drains or gurgling toilets","Sewage odors indoors or outside","Standing water over the drain field",
   "Backups into sinks, tubs, or toilets","Bright green grass over the tank or field","It's been years since your last pumping"]},
 "steps":[("Reach out","Call or send a request describing what you're seeing."),
          ("We assess","A technician inspects your system and explains the options."),
          ("We complete the work","We finish the job and leave you with a dependable system.")],
 "faqs":[("How often should I pump my septic tank?","For most households, every 3–5 years is a good rule of thumb, though it depends on tank size and how many people are in the home. We can recommend a schedule for your property."),
         ("Do you handle both repairs and replacements?","Yes. We repair individual components when that's the right call, and handle full replacements when a system has reached the end of its service life."),
         ("Do you service commercial properties?","Yes, we work with both homeowners and businesses across the Midlands.")],
 "related":[("Septic Pumping","septic-pumping.html"),("Septic Inspections","septic-inspections.html"),
            ("Well Drilling","well-drilling.html"),("Grease Interceptors","grease-interceptors.html"),
            ("Precast Tanks","precast-tanks.html"),("Contact Sharpe's","contact.html")],
 "cta_headline":"Need septic service?","cta_sub":"Call now or request service online and a local Sharpe's team member will help you find the right next step.",
},

# ---------- SEPTIC INSTALLATION ----------
{
 "file":"septic-installation.html","active":"septic-installation.html",
 "direct_answer":[('Do you install septic systems for new construction?', "Yes. We install septic systems for new construction, property additions, and replacement of older systems across the Midlands. We assess your site and walk you through the process — including the permits and approvals a new system requires — so you don't have to navigate it alone.")],
 "title":"Septic System Installation in the Midlands | Sharpe's Septic",
 "desc":"Professional septic system installation for new builds and replacements across the Midlands. Properly sized and code-aligned. Call (803) 755-1615.",
 "h1":"Septic Installation","eyebrow":"New septic systems","crumbs":SEPTIC_CRUMB,
 "service_param":"septic-installation","photo":"Septic tank installation in progress on a job site",
 "photo_key":"septic_team","photo_alt":"Sharpe's crew on a residential septic installation job site",
 "hero_copy":"Building new or replacing an old system? We install septic systems that are properly sized for your property, soil, and household so they perform for years to come.",
 "cta_label":"Request an Estimate","cta_track":"request_estimate_click",
 "context":{"eyebrow":"Done right from the start","title":"Installation built around your property",
   "body":"A septic system that's correctly sized and installed is one you can forget about. We assess your site and put in a system matched to how you actually use it.",
   "points":["Sizing based on property and household needs","Quality tanks, including precast options","Coordination for new construction or replacement","Guidance through permitting and approvals","Work completed by an experienced local crew"]},
 "steps":[("Site assessment","We evaluate your property, soil, and usage."),
          ("System design","We recommend the right system and tank for your needs."),
          ("Installation","Our crew installs and tests the system properly.")],
 "faqs":[("How long does a septic installation take?","It depends on the system and site conditions. We'll give you a clear timeline after assessing your property."),
         ("Can you install a precast tank?","Yes. We work with quality precast tanks and can discuss the best option for your install."),
         ("Do you handle replacements of old systems?","Absolutely — see our Repairs & Replacement page for failing systems.")],
 "related":[("Repairs &amp; Replacement","septic-repairs-replacement.html"),("Precast Tanks","precast-tanks.html"),
            ("Septic Inspections","septic-inspections.html")],
 "cta_headline":"Planning a new septic system?","cta_sub":"Tell us about your property and we'll help you plan the right installation.",
},

# ---------- SEPTIC REPAIRS & REPLACEMENT ----------
{
 "file":"septic-repairs-replacement.html","active":"septic-repairs-replacement.html",
 "direct_answer":[('What are the signs my septic system needs repair?', "Common warning signs include backups, sewage odors, gurgling drains, slow drains, and wet or soggy areas over the drain field. You don't have to diagnose the problem yourself — describe what you're seeing and Sharpe's will determine whether a targeted repair or a full replacement is the right next step.")],
 "title":"Septic Repairs & Replacement | Sharpe's Septic",
 "desc":"Septic repairs and full system replacement across the Midlands. From failing components to end-of-life systems. Call (803) 755-1615.",
 "h1":"Septic Repairs &amp; Replacement","eyebrow":"When something's wrong","crumbs":SEPTIC_CRUMB,
 "service_param":"septic-repair","photo":"Technician repairing a septic system component",
 "photo_key":"about_trust","photo_alt":"Sharpe's technician diagnosing and repairing a septic system in the field",
 "hero_copy":"Backups, odors, or a system that's just worn out — we diagnose the problem and recommend the most practical fix, whether that's a targeted repair or a full replacement.",
 "cta_label":"Request a Repair","cta_track":"request_estimate_click",
 "context":{"eyebrow":"Honest recommendations","title":"Repair when we can, replace when we should",
   "body":"Not every problem means a new system. We'll tell you straight whether a repair will solve it or whether replacement is the smarter long-term move. You don't have to diagnose the issue before calling — describe what you're seeing and we'll take it from there.",
   "points":["Diagnosis of backups, odors, and drainage issues","Component repairs and part replacement","Full system replacement when needed","Clear explanation of your options"]},
 "signs":{"title":"Signs you may need a repair or replacement","items":[
   "Frequent or recurring backups","Persistent sewage odors","Soggy ground or pooling over the field",
   "Slow drains throughout the house","An aging system past its expected life","Failed inspection findings"]},
 "steps":[("Diagnose","We find the root cause, not just the symptom."),
          ("Recommend","We explain repair vs. replacement and the costs involved."),
          ("Resolve","We complete the work and confirm the system is sound.")],
 "faqs":[("How do I know if I need a repair or a full replacement?","We diagnose the system first. If a repair will reliably solve the issue, that's what we recommend. If the system is failing overall, we'll explain why replacement is the better value."),
         ("Can a repair be done quickly?","Many repairs can be handled promptly. Call us and describe what's happening so we can prioritize."),
         ("What causes septic systems to fail?","Common causes include age, lack of pumping, excess water, and root intrusion. An inspection helps pinpoint the cause.")],
 "related":[("Septic Pumping","septic-pumping.html"),("Septic Installation","septic-installation.html"),
            ("Septic Inspections","septic-inspections.html")],
 "cta_headline":"Septic trouble?","cta_sub":"Call now and describe what you're seeing — we'll help you sort it out.",
},

# ---------- SEPTIC PUMPING ----------
{
 "file":"septic-pumping.html","active":"septic-pumping.html",
 "direct_answer":[('How often should a septic tank be pumped?', "Most septic tanks should be pumped every 3–5 years, depending on tank size, household size, and usage. If it has been longer than that — or you're not sure when it was last done — it's worth scheduling. Sharpe's pumps residential and commercial tanks across Columbia, Gaston, Lexington, and the surrounding Midlands.")],
 "title":"Septic Tank Pumping in the Midlands | Sharpe's Septic",
 "desc":"Reliable residential and commercial septic tank pumping across the Midlands. Prevent backups and extend system life. Call (803) 755-1615.",
 "h1":"Septic Pumping","eyebrow":"Routine maintenance","crumbs":SEPTIC_CRUMB,
 "service_param":"septic-pumping","photo":"Sharpe's pump truck servicing a septic tank",
 "photo_key":"about_trust","photo_alt":"Sharpe's crew servicing a septic system in the field",
 "hero_copy":"Regular pumping is the single best thing you can do for your septic system. We pump residential and commercial tanks on a schedule that keeps your system healthy and backups away.",
 "cta_label":"Schedule Pumping","cta_track":"request_estimate_click",
 "context":{"eyebrow":"Prevention beats repair","title":"Stay ahead of backups with routine pumping",
   "body":"Over time, solids build up in your tank. Left too long, that leads to backups and damage. Routine pumping clears it out and protects your investment. If we notice anything else while we're on site, we'll let you know and help you plan the next step.",
   "points":["Residential and commercial tanks","Scheduling based on your tank and household","Helps prevent costly backups and damage","Reminders so you don't have to track it"]},
 "signs":{"title":"Signs it's time to pump","items":[
   "It's been 3–5+ years since your last pumping","Slow drains across the house","Gurgling sounds from plumbing",
   "Odors near the tank or drain field","Standing water over the field","You're not sure when it was last done"]},
 "steps":[("Schedule","Call or request a time that works for you."),
          ("We pump","We locate and pump your tank cleanly and efficiently."),
          ("We advise","We flag anything to watch and set your next interval.")],
 "faqs":[("How often should a septic tank be pumped?","Typically every 3–5 years for an average household, but it depends on tank size and usage. We can recommend a schedule for your home."),
         ("What happens if I never pump my tank?","Solids accumulate until the system backs up or fails, which is far more expensive than routine pumping."),
         ("Do you pump commercial tanks?","Yes — we handle both residential and commercial septic pumping.")],
 "related":[("Septic Inspections","septic-inspections.html"),("Repairs &amp; Replacement","septic-repairs-replacement.html"),
            ("Grease Interceptor Pumping","grease-interceptor-pumping-inspections.html")],
 "cta_headline":"Due for a pump-out?","cta_sub":"Schedule septic pumping with a local team you can count on.",
},

# ---------- SEPTIC INSPECTIONS ----------
{
 "file":"septic-inspections.html","active":"septic-inspections.html",
 "direct_answer":[('Do I need a septic inspection when buying or selling a home?', "If the property is on a septic system, an inspection is strongly recommended before you buy or sell. It gives buyers, sellers, and realtors a clear, documented picture of the system's condition before closing, so there are no costly surprises. Sharpe's provides septic inspections across the Midlands and works with real estate timelines.")],
 "title":"Septic Inspections in the Midlands | Sharpe's Septic",
 "desc":"Documented septic system inspections for buying, selling, or maintaining property in the Midlands. Call (803) 755-1615.",
 "h1":"Septic Inspections","eyebrow":"Know your system","crumbs":SEPTIC_CRUMB,
 "service_param":"septic-inspection","photo":"Technician inspecting a septic tank and drain field",
 "hero_copy":"Buying or selling a home, or just want to know where your system stands? We provide clear, documented septic inspections so you can make decisions with confidence.",
 "cta_label":"Request an Inspection","cta_track":"request_inspection_click",
 "context":{"eyebrow":"Clarity before you commit","title":"A clear picture of your septic system",
   "body":"An inspection tells you the real condition of a system before a sale closes or before a small issue becomes a big one.",
   "points":["Inspections for buyers, sellers, realtors, and homeowners","Maintenance inspections for peace of mind","Documented findings you can share","Recommendations on any needed work"]},
 "steps":[("Request","Tell us the property and your timeline."),
          ("Inspect","We evaluate the tank, drain field, and components."),
          ("Report","You get clear findings and next-step recommendations.")],
 "faqs":[("Do I need an inspection when buying a home?","It's strongly recommended. A septic inspection can reveal costly issues before you close."),
         ("What does a septic inspection cover?","We evaluate the tank, components, and drain field, and document the overall condition of the system."),
         ("Can you inspect on a tight closing timeline?","We do our best to accommodate real estate timelines — call us and we'll work with you.")],
 "related":[("Septic Pumping","septic-pumping.html"),("Repairs &amp; Replacement","septic-repairs-replacement.html"),
            ("Well Inspections","well-inspections.html")],
 "cta_headline":"Need a septic inspection?","cta_sub":"Request an inspection and we'll get you clear answers quickly.",
},

# ---------- WELL DRILLING (category) ----------
{
 "file":"well-drilling.html","active":"well-drilling.html",
 "direct_answer":[('Do you drill new wells in the Midlands?', "Yes. Sharpe's drills and installs new wells and services existing ones across Columbia, Gaston, Lexington, and the surrounding Midlands. Whether you need a brand-new well, a repair, or an inspection before a property sale, one local team handles it all.")],
 "title":"Well Drilling & Well Services in the Midlands | Sharpe's Septic",
 "desc":"Well installation, repair and maintenance, and well inspections across the Midlands. Family owned since 1966. Call (803) 755-1615.",
 "h1":"Well Drilling &amp; Well Services","eyebrow":"Clean, dependable water","crumbs":CR_HOME,
 "service_param":"well-installation","photo":"Well drilling equipment in field",
 "photo_key":"well_frontyard","photo_alt":"Front-yard excavation for a Sharpe's well drilling project",
 "hero_copy":"From new well installation to repairs, maintenance, and inspections, Sharpe's keeps Midlands properties supplied with clean, dependable water — backed by decades of local experience.",
 "cta_label":"Schedule Well Service","cta_track":"request_estimate_click",
 "context":{"eyebrow":"Water you can rely on","title":"Complete well services under one local team",
   "body":"Your well is the source of your water — it deserves experienced care. We handle the full lifecycle, from drilling a new well to keeping an existing one running. We serve Columbia, Gaston, Lexington, and the surrounding Midlands.",
   "points":["New well installation and drilling","Repairs and ongoing maintenance","Well inspections for sales and peace of mind","Local crews who know Midlands conditions"]},
 "cards_title":"Need a new well, help with an existing well, or an inspection?","cards_eyebrow":"Choose your service","cards_cols":3,
 "cards":[
   ("Well Installation","New well drilling and installation sized for your property and water needs.","well-installation.html"),
   ("Well Repair &amp; Maintenance","Fixes and upkeep to keep your water flowing clean and steady.","well-repair-maintenance.html"),
   ("Well Inspections","Documented inspections for real estate and routine confidence.","well-inspections.html"),
 ],
 "steps":[("Reach out","Tell us what you need — a new well or service on an existing one."),
          ("We assess","We evaluate your site or system and explain the options."),
          ("We deliver","We complete the work and confirm your water is dependable.")],
 "faqs":[("Do you drill new wells?","Yes. We handle new well installation as well as repairs, maintenance, and inspections."),
         ("My water pressure dropped — can you help?","Yes, that's a common well issue. Call us and we'll diagnose the cause."),
         ("Do you inspect wells for home sales?","We do — documented well inspections are available for real estate transactions.")],
 "related":[("Well Installation","well-installation.html"),("Well Repair &amp; Maintenance","well-repair-maintenance.html"),
            ("Well Inspections","well-inspections.html"),("Septic Services","septic-services.html"),
            ("Contact Sharpe's","contact.html")],
 "cta_headline":"Need well service?","cta_sub":"Call now or request service online and a local Sharpe's team member will help.",
},

# ---------- WELL INSTALLATION ----------
{
 "file":"well-installation.html","active":"well-installation.html",
 "direct_answer":[("What's involved in installing a new well?", "Installation starts with evaluating your property to find the best location, then handling the permitting and approvals, drilling and setting the well, and running it before use so the water is clean and ready. Sharpe's manages each step for homes and businesses across the Midlands.")],
 "title":"Well Installation & Drilling | Sharpe's Septic",
 "desc":"New well drilling and installation across the Midlands, sized for your property and water needs. Call (803) 755-1615.",
 "h1":"Well Installation","eyebrow":"New wells","crumbs":WELL_CRUMB,
 "service_param":"well-installation","photo":"Well drilling rig setting up on a property",
 "photo_key":"well_tools","photo_alt":"Close-up of well drilling and service tools used by the Sharpe's crew",
 "hero_copy":"Need a new well? We drill and install wells matched to your property and water needs, so you get a clean, dependable supply for years to come.",
 "cta_label":"Request an Estimate","cta_track":"request_estimate_click",
 "context":{"eyebrow":"Built for your property","title":"A new well, done by an experienced local crew",
   "body":"Drilling a well is a long-term investment. We evaluate your site and install a well designed to deliver reliable water for your home or business.",
   "points":["Site evaluation and well siting","We walk you through siting, permitting, and approvals","Drilling and installation","Sized for household or commercial use","Experienced Midlands crews"]},
 "steps":[("Site evaluation","We assess your property and water needs."),
          ("Drilling &amp; install","We drill and install your well properly."),
          ("Testing","We confirm the well delivers dependable water.")],
 "faqs":[("How do you decide where to drill?","We evaluate your property and local conditions to site the well for the best chance of a reliable supply."),
         ("How long does well installation take?","It varies by depth and site conditions. We'll provide a timeline after assessing your property."),
         ("Can you also maintain the well afterward?","Yes — see Well Repair & Maintenance for ongoing service.")],
 "related":[("Well Repair &amp; Maintenance","well-repair-maintenance.html"),("Well Inspections","well-inspections.html"),
            ("Septic Installation","septic-installation.html")],
 "cta_headline":"Planning a new well?","cta_sub":"Tell us about your property and we'll help you plan the installation.",
},

# ---------- WELL REPAIR & MAINTENANCE ----------
{
 "file":"well-repair-maintenance.html","active":"well-repair-maintenance.html",
 "direct_answer":[('What are the signs my well needs service?', "Low or fluctuating water pressure, dirty or discolored water, air sputtering from the faucet, unusual noises, a pump that runs constantly, or a higher electric bill can all point to a well or pump problem. Sharpe's diagnoses and repairs wells across Columbia, Gaston, Lexington, and the surrounding Midlands.")],
 "title":"Well Repair & Maintenance | Sharpe's Septic",
 "desc":"Well repairs and maintenance across the Midlands — pressure issues, pumps, and routine upkeep. Call (803) 755-1615.",
 "h1":"Well Repair &amp; Maintenance","eyebrow":"Keep water flowing","crumbs":WELL_CRUMB,
 "service_param":"well-repair","photo":"Technician servicing a well pump and pressure system",
 "photo_key":"well_tools","photo_alt":"Close-up of well service tools used to repair a pump and pressure system",
 "hero_copy":"Low pressure, dirty water, or a pump that's acting up? We diagnose and repair well issues and provide maintenance to keep your water clean and steady.",
 "cta_label":"Schedule Well Service","cta_track":"request_estimate_click",
 "context":{"eyebrow":"Diagnose and fix","title":"Repairs and upkeep for dependable water",
   "body":"Wells have moving parts that wear over time. We find the cause of the problem and get your water back to normal.",
   "points":["Pressure and flow problems","Pump and component repairs","Water quality concerns","Routine maintenance to prevent issues"]},
 "signs":{"title":"Signs your well needs service","items":[
   "Low or fluctuating water pressure","Sputtering or air in the lines","Dirty, cloudy, or odd-tasting water",
   "Pump running constantly or short-cycling","Unusual noises from the pump or pressure tank","Higher electric bills from the pump","No water at all"]},
 "steps":[("Diagnose","We identify the source of the problem."),
          ("Repair","We fix the pump, pressure system, or component."),
          ("Maintain","We recommend upkeep to avoid repeat issues.")],
 "faqs":[("Why did my water pressure drop?","It can be a pump, pressure tank, or supply issue. We diagnose the specific cause and repair it."),
         ("Do you service the well pump?","Yes — pumps and pressure systems are a common part of what we repair."),
         ("How often should a well be serviced?","Periodic maintenance helps catch small issues early. We can recommend a schedule for your system.")],
 "related":[("Well Installation","well-installation.html"),("Well Inspections","well-inspections.html"),
            ("Septic Repairs &amp; Replacement","septic-repairs-replacement.html")],
 "cta_headline":"Well acting up?","cta_sub":"Call now and describe the problem — we'll help you get your water back.",
},

# ---------- WELL INSPECTIONS ----------
{
 "file":"well-inspections.html","active":"well-inspections.html",
 "direct_answer":[('When should I schedule a well inspection?', "Schedule a well inspection before buying or selling a property on a private well, or whenever you want peace of mind about your water source. It gives buyers, sellers, and realtors a documented picture of the well's condition before closing. Sharpe's provides well inspections throughout the Midlands and works with your timeline.")],
 "title":"Well Inspections | Sharpe's Septic",
 "desc":"Documented well inspections for real estate transactions and routine confidence across the Midlands. Call (803) 755-1615.",
 "h1":"Well Inspections","eyebrow":"Know your water source","crumbs":WELL_CRUMB,
 "service_param":"well-inspection","photo":"Technician inspecting a well head and components",
 "photo_key":"well_frontyard","photo_alt":"A residential well site Sharpe's evaluates before a property sale",
 "hero_copy":"Buying or selling a property with a well, or want to verify your system's condition? We provide clear, documented well inspections.",
 "cta_label":"Request an Inspection","cta_track":"request_inspection_click",
 "context":{"eyebrow":"Confidence before you commit","title":"A clear look at your well",
   "body":"A well inspection gives you a documented picture of the system's condition — essential before a sale and useful for routine peace of mind.",
   "points":["For buyers, sellers, realtors, and homeowners","Component and condition assessment","Documented findings to share","Recommendations on any needed work"]},
 "steps":[("Request","Tell us the property and your timeline."),
          ("Inspect","We evaluate the well and its components."),
          ("Report","You get clear findings and recommendations.")],
 "faqs":[("Do I need a well inspection when buying a home?","It's strongly recommended for any property on a private well, to avoid surprises after closing."),
         ("What does a well inspection include?","We assess the well and its components and document the overall condition of the system."),
         ("Can you inspect on a closing timeline?","We do our best to accommodate real estate timelines — just let us know your dates.")],
 "related":[("Well Repair &amp; Maintenance","well-repair-maintenance.html"),("Well Installation","well-installation.html"),
            ("Septic Inspections","septic-inspections.html")],
 "cta_headline":"Need a well inspection?","cta_sub":"Request an inspection and we'll get you clear answers quickly.",
},

# ---------- GREASE INTERCEPTORS (category) ----------
{
 "file":"grease-interceptors.html","active":"grease-interceptors.html",
 "direct_answer":[('What businesses need grease interceptor service?', "Restaurants, commercial kitchens, hotels, schools, churches and fellowship halls, automotive businesses, and dental offices all rely on grease interceptors to stay compliant and avoid backups. Sharpe's installs, pumps, and inspects interceptors for businesses across the Midlands.")],
 "title":"Grease Interceptor Services for Commercial Kitchens | Sharpe's Septic",
 "desc":"Grease interceptor installation, pumping, and inspections for restaurants and commercial kitchens across the Midlands. Call (803) 755-1615.",
 "h1":"Grease Interceptors","eyebrow":"For restaurants &amp; commercial kitchens","crumbs":CR_HOME,
 "service_param":"grease-interceptor-installation","photo":"Grease interceptor installation or maintenance",
 "photo_key":"grease_digging","photo_alt":"Excavation work for a commercial grease interceptor installation",
 "hero_copy":"Restaurants and commercial kitchens rely on grease interceptors to stay compliant and avoid messy backups. Sharpe's installs, pumps, and inspects interceptors so your kitchen keeps running.",
 "cta_label":"Request Commercial Service","cta_track":"request_commercial_service_click",
 "context":{"eyebrow":"Keep your kitchen running","title":"Grease interceptor service done right",
   "body":"A neglected grease interceptor means odors, backups, and compliance headaches. We help commercial kitchens stay ahead of all three. We serve restaurants, hotels, schools, fellowship halls, and other commercial kitchens across the Midlands.",
   "points":["For restaurants, hotels, schools, fellowship halls, and more","Installation for new and existing kitchens","Scheduled pumping to prevent backups","Inspections and condition checks","Service that works around your hours where possible"]},
 "cards_title":"Explore grease interceptor services","cards_eyebrow":"Choose your service","cards_cols":2,
 "cards":[
   ("Grease Interceptor Installation","Properly sized interceptor installation for new and existing commercial kitchens.","grease-interceptor-installation.html"),
   ("Pumping &amp; Inspections","Scheduled pumping and inspections to keep your interceptor compliant and trouble-free.","grease-interceptor-pumping-inspections.html"),
 ],
 "steps":[("Reach out","Tell us about your kitchen and what you need."),
          ("We assess","We recommend the right install or service schedule."),
          ("We service","We keep your interceptor working and compliant.")],
 "faqs":[("How often should a grease interceptor be pumped?","It depends on your kitchen's volume and local requirements. We'll recommend a schedule that keeps you compliant and backup-free."),
         ("Do you install new interceptors?","Yes — we install properly sized interceptors for new and existing commercial kitchens."),
         ("Can you work around our business hours?","We do our best to schedule service with minimal disruption to your operations.")],
 "related":[("Grease Interceptor Installation","grease-interceptor-installation.html"),
            ("Pumping &amp; Inspections","grease-interceptor-pumping-inspections.html"),
            ("Septic Pumping","septic-pumping.html"),("Precast Tanks","precast-tanks.html"),
            ("Contact Sharpe's","contact.html")],
 "cta_headline":"Need grease interceptor service?","cta_sub":"Call now or request commercial service and we'll keep your kitchen running.",
},

# ---------- GREASE INTERCEPTOR INSTALLATION ----------
{
 "file":"grease-interceptor-installation.html","active":"grease-interceptor-installation.html",
 "direct_answer":[('Do you install grease interceptors for new and existing kitchens?', "Yes. Sharpe's installs properly sized grease interceptors — typically 1,000 to 3,000 gallons — for new builds and existing commercial kitchens, and coordinates the connection and final inspection. We serve commercial kitchens across the Midlands.")],
 "title":"Grease Interceptor Installation | Sharpe's Septic",
 "desc":"Properly sized grease interceptor installation for restaurants and commercial kitchens across the Midlands. Call (803) 755-1615.",
 "h1":"Grease Interceptor Installation","eyebrow":"New &amp; existing kitchens","crumbs":GREASE_CRUMB,
 "service_param":"grease-interceptor-installation","photo":"Grease interceptor being installed at a commercial kitchen",
 "photo_key":"grease_backing","photo_alt":"Sharpe's service truck positioned for a commercial grease interceptor job",
 "hero_copy":"Opening a kitchen or upgrading your setup? We install grease interceptors sized for your operation so you stay compliant and avoid backups.",
 "cta_label":"Request Commercial Service","cta_track":"request_commercial_service_click",
 "context":{"eyebrow":"Sized for your operation","title":"The right interceptor for your kitchen",
   "body":"An undersized or poorly installed interceptor causes problems fast. We assess your kitchen and install a system that fits how you operate.",
   "points":["Sizing based on your kitchen's volume — typically 1,000 to 3,000 gallons","Installation for new builds and upgrades","Setup aligned with local requirements","Experienced commercial service"]},
 "steps":[("Assess","We evaluate your kitchen and requirements."),
          ("Install","We install a correctly sized interceptor."),
          ("Schedule service","We set up ongoing pumping and inspections.")],
 "faqs":[("How do I know what size interceptor I need?","It depends on your kitchen's volume and local code. We'll assess your operation and recommend the right size."),
         ("Can you install in an existing kitchen?","Yes — we handle both new builds and upgrades to existing kitchens."),
         ("Do you also handle ongoing service?","Yes, see our Pumping & Inspections page for scheduled maintenance.")],
 "related":[("Pumping &amp; Inspections","grease-interceptor-pumping-inspections.html"),
            ("Precast Tanks","precast-tanks.html"),("Septic Installation","septic-installation.html")],
 "cta_headline":"Planning a grease interceptor install?","cta_sub":"Tell us about your kitchen and we'll recommend the right setup.",
},

# ---------- GREASE INTERCEPTOR PUMPING & INSPECTIONS ----------
{
 "file":"grease-interceptor-pumping-inspections.html","active":"grease-interceptor-pumping-inspections.html",
 "direct_answer":[('How often should a grease interceptor be pumped?', "Most interceptors are pumped on a recurring schedule based on your kitchen's volume and local requirements. Staying on schedule prevents odors, backups, and compliance issues. Sharpe's pumps and inspects interceptors across the Midlands and provides documentation to support your compliance.")],
 "title":"Grease Interceptor Pumping & Inspections | Sharpe's Septic",
 "desc":"Scheduled grease interceptor pumping and inspections for commercial kitchens across the Midlands. Stay compliant and backup-free. Call (803) 755-1615.",
 "h1":"Grease Interceptor Pumping &amp; Inspections","eyebrow":"Stay compliant &amp; clear","crumbs":GREASE_CRUMB,
 "service_param":"grease-interceptor-pumping","photo":"Grease interceptor being pumped at a restaurant",
 "photo_key":"grease_backing","photo_alt":"Sharpe's truck positioned to pump and service a commercial grease interceptor",
 "hero_copy":"Keep your kitchen compliant and backup-free with scheduled grease interceptor pumping and inspections from a local team that works around your operation.",
 "cta_label":"Request Commercial Service","cta_track":"request_commercial_service_click",
 "context":{"eyebrow":"Routine keeps you running","title":"Scheduled pumping and inspections",
   "body":"Grease builds up steadily. Staying on a pumping and inspection schedule prevents odors, backups, and compliance issues before they start.",
   "points":["Scheduled pumping on the right interval","Inspections and condition checks","Documentation to support compliance","Service scheduled around your hours where possible"]},
 "signs":{"title":"Signs your interceptor needs service","items":[
   "Slow drains in the kitchen","Odors near drains or the interceptor","Grease showing up where it shouldn't",
   "It's been a while since the last pump-out","An upcoming compliance check","Backups during busy service"]},
 "steps":[("Schedule","We set a pumping and inspection interval for your kitchen."),
          ("We service","We pump and inspect with minimal disruption."),
          ("We document","You get records to support compliance.")],
 "faqs":[("How often does my interceptor need pumping?","It depends on volume and local requirements. We'll recommend an interval that keeps you compliant and trouble-free."),
         ("Do you provide documentation?","Yes — we can document service to help support your compliance requirements."),
         ("Can you service during off-hours?","We do our best to schedule around your busiest times.")],
 "related":[("Grease Interceptor Installation","grease-interceptor-installation.html"),
            ("Septic Pumping","septic-pumping.html"),("Contact Sharpe's","contact.html")],
 "cta_headline":"Time to service your interceptor?","cta_sub":"Request commercial service and we'll keep your kitchen compliant.",
},

# ---------- PRECAST TANKS ----------
{
 "file":"precast-tanks.html","active":"precast-tanks.html",
 "direct_answer":[("What precast products does Sharpe's make?", "Sharpe's manufactures and installs precast septic tanks, grease interceptors, pump tanks, distribution boxes, tank lids, and pole pads in a range of sizes. Because we run our own plant, we can supply the right component for new installs and replacements across the Midlands.")],
 "title":"Precast Tanks | Sharpe's Septic",
 "desc":"Quality precast septic and water tanks for installations and replacements across the Midlands. Call (803) 755-1615.",
 "h1":"Precast Tanks","eyebrow":"Durable, quality tanks","crumbs":CR_HOME,
 "service_param":"precast-tanks","photo":"Precast tanks in the equipment yard",
 "photo_key":"precast_frontyard","photo_alt":"Job site where a Sharpe's precast septic tank is being set",
 "hero_copy":"Quality precast tanks are the backbone of a dependable septic system. Sharpe's supplies and installs durable precast tanks for new installations and replacements.",
 "cta_label":"Request Product Information","cta_track":"request_estimate_click",
 "context":{"eyebrow":"Built to last","title":"Precast tanks you can rely on",
   "body":"A solid tank is the foundation of a system that lasts. We work with quality precast tanks and can help you choose the right one for your project.",
   "points":["Precast septic tanks and pump tanks","Grease interceptors","Distribution boxes, tank lids, and pole pads","Made in our own plant for new installs and replacements"]},
 "steps":[("Discuss","Tell us about your project and needs."),
          ("Select","We help you choose the right precast tank."),
          ("Install","We install it as part of your system.")],
 "faqs":[("Why choose a precast tank?","Precast tanks are durable and well-suited to long-term septic performance. We'll help you decide if it's right for your project."),
         ("Do you install the tanks you supply?","Yes — precast tanks are installed as part of our septic installation and replacement work."),
         ("Can you replace an old tank with a precast one?","Yes, that's a common part of our replacement work.")],
 "related":[("Septic Installation","septic-installation.html"),("Repairs &amp; Replacement","septic-repairs-replacement.html"),
            ("Grease Interceptor Installation","grease-interceptor-installation.html")],
 "cta_headline":"Need a precast tank?","cta_sub":"Tell us about your project and we'll help you choose the right tank.",
},

]
